import { NgModule } from '@angular/core';
import {
  NbThemeModule,
  NbLayoutModule,
  NbButtonModule,
  NbSelectModule,
  NbRadioModule,
  NbIconModule,
  NbSidebarModule,
  NbCardModule,
  NbInputModule,
  NbCheckboxModule,
  NbMenuModule,
  NbToastrModule,
  NbSpinnerModule,
  NbContextMenuModule,
  NbDialogModule,
  NbDatepickerModule,
  NbPopoverModule,
  NbStepperModule,
  NbListModule,
  NbAccordionModule,
  NbTabsetModule,
  NbBadgeModule,
  NbRouteTabsetModule,
} from '@nebular/theme';
import { NbEvaIconsModule } from '@nebular/eva-icons';

@NgModule({
  declarations: [],
  imports: [
    NbThemeModule,
    NbLayoutModule,
    NbButtonModule,
    NbSelectModule,
    NbRadioModule,
    NbPopoverModule,
    NbAccordionModule,
    NbCheckboxModule,
    NbListModule,
    NbCardModule,
    NbEvaIconsModule,
    NbIconModule,
    NbSpinnerModule,
    NbStepperModule,
    NbInputModule,
    NbRouteTabsetModule,
    NbContextMenuModule,
    NbToastrModule.forRoot(),
    NbDialogModule.forRoot(),
    NbMenuModule.forRoot(),
    NbToastrModule.forRoot(),
    NbSidebarModule.forRoot(),
    NbThemeModule.forRoot(),
    NbDatepickerModule.forRoot(),
  ],
  exports: [
    NbThemeModule,
    NbLayoutModule,
    NbButtonModule,
    NbRouteTabsetModule,
    NbSelectModule,
    NbToastrModule,
    NbLayoutModule,
    NbStepperModule,
    NbRadioModule,
    NbAccordionModule,
    NbMenuModule,
    NbListModule,
    NbThemeModule,
    NbCardModule,
    NbIconModule,
    NbEvaIconsModule,
    NbDatepickerModule,
    NbContextMenuModule,
    NbSidebarModule,
    NbInputModule,
    NbPopoverModule,
    NbCheckboxModule,
    NbDialogModule,
    NbAccordionModule,
    NbTabsetModule,
    NbBadgeModule,
  ],
})
export class NebularModule {}
