import { NgModule } from '@angular/core';
import {
  NbThemeModule,
  NbLayoutModule,
  NbButtonModule,
  NbSelectModule,
  NbRadioModule,
  NbIconModule,
  NbSidebarModule,
  NbCardModule,
  NbInputModule,
  NbCheckboxModule,
  NbMenuModule,
  NbToastrModule,
  NbSpinnerModule,
  NbContextMenuModule,
  NbDialogModule,
  NbDatepickerModule,
} from '@nebular/theme';
import { NbEvaIconsModule } from '@nebular/eva-icons';

@NgModule({
  declarations: [],
  imports: [
    NbThemeModule,
    NbLayoutModule,
    NbButtonModule,
    NbSelectModule,
    NbRadioModule,
    NbCheckboxModule,
    NbCardModule,
    NbEvaIconsModule,
    NbIconModule,
    NbSpinnerModule,
    NbInputModule,
    NbContextMenuModule,
    NbDialogModule.forRoot(),
    NbMenuModule.forRoot(),
    NbToastrModule.forRoot(),
    NbSidebarModule.forRoot(),
    NbThemeModule.forRoot(),
    NbDatepickerModule.forRoot(),
  ],
  exports: [
    NbThemeModule,
    NbLayoutModule,
    NbButtonModule,
    NbSelectModule,
    NbLayoutModule,
    NbRadioModule,
    NbMenuModule,
    NbThemeModule,
    NbCardModule,
    NbIconModule,
    NbEvaIconsModule,
    NbDatepickerModule,
    NbContextMenuModule,
    NbSidebarModule,
    NbInputModule,
    NbCheckboxModule,
    NbDialogModule,
  ],
})
export class AppNebularModule {}
