INSERT INTO `msg_audit_database`.`FacCrit` (`id`, `reference_id`, `name`) VALUES ('1', NULL, 'Effektivität');
INSERT INTO `msg_audit_database`.`FacCrit` (`id`, `reference_id`, `name`) VALUES ('2', NULL, 'Effizienz');
INSERT INTO `msg_audit_database`.`FacCrit` (`id`, `reference_id`, `name`) VALUES ('3', NULL, 'Zufriedenheit');
INSERT INTO `msg_audit_database`.`FacCrit` (`id`, `reference_id`, `name`) VALUES ('4', NULL, 'Risikofreiheit');
INSERT INTO `msg_audit_database`.`FacCrit` (`id`, `reference_id`, `name`) VALUES ('5', NULL, 'Lieferbestandteile');
INSERT INTO `msg_audit_database`.`FacCrit` (`id`, `reference_id`, `name`) VALUES ('6', NULL, 'Funktionale Tauglichkeit');
INSERT INTO `msg_audit_database`.`FacCrit` (`id`, `reference_id`, `name`) VALUES ('7', NULL, 'Performanz, Effizienz');
INSERT INTO `msg_audit_database`.`FacCrit` (`id`, `reference_id`, `name`) VALUES ('8', NULL, 'Austauschbarkeit, Übertragbarkeit');
INSERT INTO `msg_audit_database`.`FacCrit` (`id`, `reference_id`, `name`) VALUES ('9', NULL, 'Benutzbarkeit');
INSERT INTO `msg_audit_database`.`FacCrit` (`id`, `reference_id`, `name`) VALUES ('10', NULL, 'Zuverlässigkeit');
INSERT INTO `msg_audit_database`.`FacCrit` (`id`, `reference_id`, `name`) VALUES ('11', NULL, 'Sicherheit');
INSERT INTO `msg_audit_database`.`FacCrit` (`id`, `reference_id`, `name`) VALUES ('12', NULL, 'Wartbarkeit');
INSERT INTO `msg_audit_database`.`FacCrit` (`id`, `reference_id`, `name`) VALUES ('13', NULL, 'Portabilität');
INSERT INTO `msg_audit_database`.`FacCrit` (`id`, `reference_id`, `name`) VALUES ('14', NULL, 'Sonstige Anforderungen');
INSERT INTO `msg_audit_database`.`FacCrit` (`reference_id`, `name`) VALUES ('3', 'Nützlichkeit');
INSERT INTO `msg_audit_database`.`FacCrit` (`reference_id`, `name`) VALUES ('3', 'Vertrauen');
INSERT INTO `msg_audit_database`.`FacCrit` (`reference_id`, `name`) VALUES ('3', 'Wohlgefälligkeit');
INSERT INTO `msg_audit_database`.`FacCrit` (`reference_id`, `name`) VALUES ('3', 'Komfort');
INSERT INTO `msg_audit_database`.`FacCrit` (`reference_id`, `name`) VALUES ('4', 'Verringerung der ökonomischen Risiken');
INSERT INTO `msg_audit_database`.`FacCrit` (`reference_id`, `name`) VALUES ('4', 'Verringerung der Risiken hinsichtlich Gesundheit und Sicherheit');
INSERT INTO `msg_audit_database`.`FacCrit` (`reference_id`, `name`) VALUES ('4', 'Verringerung der Umweltrisiken');
INSERT INTO `msg_audit_database`.`FacCrit` (`reference_id`, `name`) VALUES ('5', 'Komplette Abdeckung aller Umgebungsanforderungen');
INSERT INTO `msg_audit_database`.`FacCrit` (`reference_id`, `name`) VALUES ('5', 'Flexibilität');
INSERT INTO `msg_audit_database`.`FacCrit` (`reference_id`, `name`) VALUES ('6', 'Funktionale Vollständigkei');
INSERT INTO `msg_audit_database`.`FacCrit` (`reference_id`, `name`) VALUES ('6', 'Funktionale Richtigkeit');
INSERT INTO `msg_audit_database`.`FacCrit` (`reference_id`, `name`) VALUES ('6', 'Funktionale Angemessenheit');
INSERT INTO `msg_audit_database`.`FacCrit` (`reference_id`, `name`) VALUES ('7', 'Antwortzeitverhalten');
INSERT INTO `msg_audit_database`.`FacCrit` (`reference_id`, `name`) VALUES ('7', 'Ressourcenverbrauch');
INSERT INTO `msg_audit_database`.`FacCrit` (`reference_id`, `name`) VALUES ('7', 'Kapazität');
INSERT INTO `msg_audit_database`.`FacCrit` (`reference_id`, `name`) VALUES ('8', 'Koexistenz');
INSERT INTO `msg_audit_database`.`FacCrit` (`reference_id`, `name`) VALUES ('8', 'Interoperabilität');
INSERT INTO `msg_audit_database`.`FacCrit` (`reference_id`, `name`) VALUES ('9', 'Angemessenheit Erkennbarkeit');
INSERT INTO `msg_audit_database`.`FacCrit` (`reference_id`, `name`) VALUES ('9', 'Erlernbarkeit');
INSERT INTO `msg_audit_database`.`FacCrit` (`reference_id`, `name`) VALUES ('9', 'Bedienbarkeit');
INSERT INTO `msg_audit_database`.`FacCrit` (`reference_id`, `name`) VALUES ('9', 'auf Anwender bezogene Fehlervorbeugung');
INSERT INTO `msg_audit_database`.`FacCrit` (`reference_id`, `name`) VALUES ('9', 'Ästhetik der Benutzeroberfläche');
INSERT INTO `msg_audit_database`.`FacCrit` (`reference_id`, `name`) VALUES ('9', 'Zugänglichkeit / Barrierefreiheit');
INSERT INTO `msg_audit_database`.`FacCrit` (`reference_id`, `name`) VALUES ('10', 'Reife');
INSERT INTO `msg_audit_database`.`FacCrit` (`reference_id`, `name`) VALUES ('10', 'Verfügbarkeit');
INSERT INTO `msg_audit_database`.`FacCrit` (`reference_id`, `name`) VALUES ('10', 'Fehlertoleranz');
INSERT INTO `msg_audit_database`.`FacCrit` (`reference_id`, `name`) VALUES ('10', 'Wiedeherstellbarkeit');
INSERT INTO `msg_audit_database`.`FacCrit` (`reference_id`, `name`) VALUES ('11', 'Vertraulichkeit, Zugriffsrechte');
INSERT INTO `msg_audit_database`.`FacCrit` (`reference_id`, `name`) VALUES ('11', 'Integrität');
INSERT INTO `msg_audit_database`.`FacCrit` (`reference_id`, `name`) VALUES ('11', 'Nachweisbarkeit, Schutz vor fremdem Zugriff');
INSERT INTO `msg_audit_database`.`FacCrit` (`reference_id`, `name`) VALUES ('11', 'Haftung');
INSERT INTO `msg_audit_database`.`FacCrit` (`reference_id`, `name`) VALUES ('11', 'Authentizität, Glaubwürdigkeit');
INSERT INTO `msg_audit_database`.`FacCrit` (`reference_id`, `name`) VALUES ('12', ' Modularität');
INSERT INTO `msg_audit_database`.`FacCrit` (`reference_id`, `name`) VALUES ('12', 'Wiederverwendbarkeit');
INSERT INTO `msg_audit_database`.`FacCrit` (`reference_id`, `name`) VALUES ('12', 'Analysierbarkeit');
INSERT INTO `msg_audit_database`.`FacCrit` (`reference_id`, `name`) VALUES ('12', 'Modifizierbarkeit');
INSERT INTO `msg_audit_database`.`FacCrit` (`reference_id`, `name`) VALUES ('12', 'Prüfbarkeit');
INSERT INTO `msg_audit_database`.`FacCrit` (`reference_id`, `name`) VALUES ('13', 'Anpassbarkeit');
INSERT INTO `msg_audit_database`.`FacCrit` (`reference_id`, `name`) VALUES ('13', 'Installierbarkeit');
INSERT INTO `msg_audit_database`.`FacCrit` (`reference_id`, `name`) VALUES ('13', 'Austauschbarkeit');
