INSERT INTO `msg_audit_database`.`fac_crit` (`id`, `reference_id`, `name`, `goal`) VALUES ('1', NULL, 'Effektivität', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`id`, `reference_id`, `name`, `goal`) VALUES ('2', NULL, 'Effizienz', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`id`, `reference_id`, `name`, `goal`) VALUES ('3', NULL, 'Zufriedenheit', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`id`, `reference_id`, `name`, `goal`) VALUES ('4', NULL, 'Risikofreiheit', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`id`, `reference_id`, `name`, `goal`) VALUES ('5', NULL, 'Lieferbestandteile', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`id`, `reference_id`, `name`, `goal`) VALUES ('6', NULL, 'Funktionale Tauglichkeit', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`id`, `reference_id`, `name`, `goal`) VALUES ('7', NULL, 'Performanz, Effizienz', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`id`, `reference_id`, `name`, `goal`) VALUES ('8', NULL, 'Austauschbarkeit, Übertragbarkeit', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`id`, `reference_id`, `name`, `goal`) VALUES ('9', NULL, 'Benutzbarkeit', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`id`, `reference_id`, `name`, `goal`) VALUES ('10', NULL, 'Zuverlässigkeit', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`id`, `reference_id`, `name`, `goal`) VALUES ('11', NULL, 'Sicherheit', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`id`, `reference_id`, `name`, `goal`) VALUES ('12', NULL, 'Wartbarkeit', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`id`, `reference_id`, `name`, `goal`) VALUES ('13', NULL, 'Portabilität', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`id`, `reference_id`, `name`, `goal`) VALUES ('14', NULL, 'Sonstige Anforderungen', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`reference_id`, `name`, `goal`) VALUES ('3', 'Nützlichkeit', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`reference_id`, `name`, `goal`) VALUES ('3', 'Vertrauen', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`reference_id`, `name`, `goal`) VALUES ('3', 'Wohlgefälligkeit', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`reference_id`, `name`, `goal`) VALUES ('3', 'Komfort', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`reference_id`, `name`, `goal`) VALUES ('4', 'Verringerung der ökonomischen Risiken', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`reference_id`, `name`, `goal`) VALUES ('4', 'Verringerung der Risiken hinsichtlich Gesundheit und Sicherheit', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`reference_id`, `name`, `goal`) VALUES ('4', 'Verringerung der Umweltrisiken', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`reference_id`, `name`, `goal`) VALUES ('5', 'Komplette Abdeckung aller Umgebungsanforderungen', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`reference_id`, `name`, `goal`) VALUES ('5', 'Flexibilität', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`reference_id`, `name`, `goal`) VALUES ('6', 'Funktionale Vollständigkeit', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`reference_id`, `name`, `goal`) VALUES ('6', 'Funktionale Richtigkeit', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`reference_id`, `name`, `goal`) VALUES ('6', 'Funktionale Angemessenheit', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`reference_id`, `name`, `goal`) VALUES ('7', 'Antwortzeitverhalten', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`reference_id`, `name`, `goal`) VALUES ('7', 'Ressourcenverbrauch', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`reference_id`, `name`, `goal`) VALUES ('7', 'Kapazität', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`reference_id`, `name`, `goal`) VALUES ('8', 'Koexistenz', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`reference_id`, `name`, `goal`) VALUES ('8', 'Interoperabilität', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`reference_id`, `name`, `goal`) VALUES ('9', 'Angemessenheit Erkennbarkeit', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`reference_id`, `name`, `goal`) VALUES ('9', 'Erlernbarkeit', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`reference_id`, `name`, `goal`) VALUES ('9', 'Bedienbarkeit', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`reference_id`, `name`, `goal`) VALUES ('9', 'auf Anwender bezogene Fehlervorbeugung', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`reference_id`, `name`, `goal`) VALUES ('9', 'Ästhetik der Benutzeroberfläche', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`reference_id`, `name`, `goal`) VALUES ('9', 'Zugänglichkeit / Barrierefreiheit', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`reference_id`, `name`, `goal`) VALUES ('10', 'Reife', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`reference_id`, `name`, `goal`) VALUES ('10', 'Verfügbarkeit', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`reference_id`, `name`, `goal`) VALUES ('10', 'Fehlertoleranz', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`reference_id`, `name`, `goal`) VALUES ('10', 'Wiedeherstellbarkeit', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`reference_id`, `name`, `goal`) VALUES ('11', 'Vertraulichkeit, Zugriffsrechte', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`reference_id`, `name`, `goal`) VALUES ('11', 'Integrität', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`reference_id`, `name`, `goal`) VALUES ('11', 'Nachweisbarkeit, Schutz vor fremdem Zugriff', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`reference_id`, `name`, `goal`) VALUES ('11', 'Haftung', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`reference_id`, `name`, `goal`) VALUES ('11', 'Authentizität, Glaubwürdigkeit', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`reference_id`, `name`, `goal`) VALUES ('12', ' Modularität', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`reference_id`, `name`, `goal`) VALUES ('12', 'Wiederverwendbarkeit', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`reference_id`, `name`, `goal`) VALUES ('12', 'Analysierbarkeit', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`reference_id`, `name`, `goal`) VALUES ('12', 'Modifizierbarkeit', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`reference_id`, `name`, `goal`) VALUES ('12', 'Prüfbarkeit', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`reference_id`, `name`, `goal`) VALUES ('13', 'Anpassbarkeit', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`reference_id`, `name`, `goal`) VALUES ('13', 'Installierbarkeit', 'dummyGoal');
INSERT INTO `msg_audit_database`.`fac_crit` (`reference_id`, `name`, `goal`) VALUES ('13', 'Austauschbarkeit', 'dummyGoal');
