INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('1', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('1', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('1', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('1', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('1', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('1', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('1', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('2', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('2', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('2', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('2', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('2', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('2', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('2', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('3', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('3', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('3', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('3', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('3', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('3', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('3', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('4', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('4', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('4', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('4', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('4', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('4', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('4', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('5', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('5', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('5', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('5', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('5', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('5', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('5', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('6', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('6', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('6', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('6', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('6', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('6', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('6', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('7', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('7', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('7', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('7', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('7', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('7', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('7', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('8', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('8', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('8', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('8', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('8', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('8', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('8', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('9', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('9', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('9', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('9', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('9', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('9', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('9', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('10', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('10', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('10', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('10', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('10', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('10', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('10', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('11', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('11', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('11', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('11', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('11', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('11', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('11', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('12', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('12', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('12', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('12', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('12', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('12', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('12', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('13', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('13', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('13', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('13', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('13', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('13', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('13', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('14', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('14', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('14', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('14', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('14', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('14', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('14', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('15', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('15', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('15', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('15', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('15', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('15', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('15', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('16', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('16', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('16', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('16', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('16', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('16', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('16', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('17', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('17', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('17', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('17', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('17', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('17', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('17', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('18', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('18', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('18', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('18', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('18', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('18', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('18', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('19', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('19', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('19', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('19', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('19', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('19', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('19', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('20', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('20', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('20', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('20', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('20', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('20', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('20', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('21', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('21', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('21', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('21', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('21', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('21', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('21', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('22', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('22', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('22', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('22', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('22', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('22', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('22', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('23', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('23', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('23', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('23', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('23', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('23', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('23', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('24', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('24', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('24', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('24', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('24', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('24', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('24', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('25', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('25', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('25', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('25', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('25', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('25', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('25', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('26', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('26', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('26', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('26', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('26', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('26', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('26', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('27', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('27', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('27', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('27', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('27', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('27', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('27', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('28', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('28', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('28', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('28', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('28', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('28', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('28', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('29', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('29', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('29', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('29', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('29', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('29', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('29', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('30', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('30', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('30', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('30', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('30', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('30', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('30', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('31', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('31', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('31', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('31', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('31', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('31', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('31', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('32', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('32', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('32', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('32', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('32', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('32', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('32', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('33', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('33', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('33', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('33', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('33', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('33', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('33', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('34', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('34', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('34', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('34', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('34', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('34', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('34', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('35', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('35', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('35', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('35', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('35', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('35', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('35', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('36', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('36', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('36', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('36', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('36', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('36', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('36', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('37', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('37', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('37', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('37', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('37', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('37', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('37', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('38', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('38', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('38', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('38', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('38', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('38', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('38', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('39', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('39', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('39', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('39', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('39', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('39', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('39', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('40', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('40', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('40', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('40', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('40', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('40', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('40', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('41', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('41', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('41', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('41', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('41', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('41', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('41', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('42', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('42', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('42', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('42', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('42', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('42', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('42', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('43', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('43', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('43', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('43', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('43', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('43', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('43', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('44', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('44', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('44', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('44', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('44', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('44', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('44', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('45', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('45', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('45', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('45', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('45', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('45', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('45', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('46', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('46', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('46', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('46', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('46', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('46', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('46', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('47', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('47', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('47', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('47', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('47', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('47', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('47', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('48', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('48', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('48', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('48', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('48', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('48', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('48', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('49', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('49', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('49', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('49', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('49', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('49', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('49', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('50', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('50', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('50', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('50', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('50', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('50', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('50', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('51', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('51', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('51', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('51', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('51', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('51', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('51', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('52', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('52', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('52', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('52', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('52', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('52', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('52', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('53', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('53', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('53', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('53', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('53', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('53', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('53', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('54', 'Existiert eine Planung, um das Qualitätskriterium in der Anwendung zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('54', 'Werden konkrete Maßnahmen ergriffen, um das Qualitätskriterium in der Anwendung    zu steigern?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('54', 'Werden konkrete Gegenmaßnahmen ergriffen, wenn es beim Ablauf der Maßnahmen zu Problemen kommt?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('54', 'Werden die Maßnahmen überwacht?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('54', 'Existieren Maßnahmen, um die Effektivität und Effizienz der durchgeführten Maßnahmen sicherzustellen?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('54', 'Werden die Ergebnisse aus der Überprüfung und Überwachung gesichert?');
INSERT INTO `msg_audit_database`.`question` (`faccrit_id`, `text_de`) VALUES ('54', 'Werden die Ergebnisse aus der Überprüfung und Überwachung genutzt um das Vorgehen zu verbessern?');

