name: Java Backend Build

on: 
  push:
    paths:
      - "java-backend/**"
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./java-backend

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        working-directory: ${{env.working-directory}}

