name: Angular Frontend Build
on:
  push:
    paths:
      - "ng-frontend/**"
jobs:
  ubuntu-build:
    runs-on: ubuntu-16.04
    env:
      working-directory: ./ng-frontend

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Packages
        run: npm i
        working-directory: ${{env.working-directory}}

      - name: Install Angular CLI
        run: npm i -g @angular/cli
        working-directory: ${{env.working-directory}}

      - name: Run e2e Tests
        uses: cypress-io/github-action@v1
        with:
          working-directory: ${{env.working-directory}}
          start: ng serve
          wait-on: http://localhost:4200
          wait-on-timeout: 300

      - name: Run Unit Tests
        run: ng test --watch=false --browsers=ChromeHeadless
        working-directory: ${{env.working-directory}}

      - name: Deploy Documentation to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.4.9
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages
          folder: ng-frontend/documentation
